meta_product_name: "Actionee"
meta_title: "Actionee - Your path to financial success."
meta_description: "The website that will give you the tools and insights to make smarter investments. Through our advanced filtering tool, find companies that fit your values and keep track of noteworthy investments. Join us now and meet our vibrant community of investors."
meta_image: "cover.png" # should exist in `app/assets/images/`
